version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: backdev:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_USER=user_db
      - DB_PASSWORD=1234
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=backdev
      - JWT_SECRET=secret_string_SV1Stail
      
  db:
    image: postgres:14-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user_db        
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: backdev            
    ports:
      - "5430:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
  test:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: builder  
    command: go test ./... -v

volumes:
  db_data:

networks:
  app-network:
